env:
  CONTAINER_REGISTRY: us-docker.pkg.dev/spinnaker-community/docker
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
jobs:
  branch-build:
    if: startsWith(github.repository, 'spinnaker/')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: '17

          11

          '
    - continue-on-error: true
      id: build_variables
      name: Prepare build variables
      run: 'echo REPO="${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

        echo VERSION="$(git describe --tags --abbrev=0 --match=''v[0-9]*'' | cut -c2-)-dev-${GITHUB_REF_NAME}-$(git
        rev-parse --short HEAD)-$(date --utc +''%Y%m%d%H%M'')" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_version: ${{ steps.build_variables.outputs.VERSION }}
      name: Build
      run: ./gradlew build --stacktrace ${{ steps.build_variables.outputs.REPO }}-web:installDist
    - continue-on-error: true
      if: startsWith(github.repository, 'spinnaker/')
      name: Login to GAR
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GAR_JSON_KEY }}
        registry: us-docker.pkg.dev
        username: _json_key
    - continue-on-error: true
      if: startsWith(github.repository, 'spinnaker/')
      name: Build and publish slim container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.slim
        platforms: linux/amd64,linux/arm64
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:${{ github.ref_name }}-latest-unvalidated"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-unvalidated"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          github.ref_name }}-latest-unvalidated-slim"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-unvalidated-slim"

          '
    - continue-on-error: true
      if: startsWith(github.repository, 'spinnaker/')
      name: Build and publish ubuntu container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.ubuntu
        platforms: linux/amd64,linux/arm64
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:${{ github.ref_name }}-latest-unvalidated-ubuntu"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-unvalidated-ubuntu"

          '
    - continue-on-error: true
      if: startsWith(github.repository, 'spinnaker/')
      name: Build and publish slim JRE 11 container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.java11.slim
        platforms: linux/amd64,linux/arm64
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:${{ github.ref_name }}-latest-java11-unvalidated"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-java11-unvalidated"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          github.ref_name }}-latest-java11-unvalidated-slim"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-java11-unvalidated-slim"

          '
    - continue-on-error: true
      if: startsWith(github.repository, 'spinnaker/')
      name: Build and publish ubuntu JRE 11 container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.java11.ubuntu
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:${{ github.ref_name }}-latest-java11-unvalidated-ubuntu"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-java11-unvalidated-ubuntu"

          '
name: Branch Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
