env:
  CONTAINER_REGISTRY: us-docker.pkg.dev/spinnaker-community/docker
  GRADLE_ARGS: -x :kayenta-integration-tests:test
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: '17

          11

          '
    - continue-on-error: true
      id: build_variables
      name: Prepare build variables
      run: 'echo REPO="${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

        echo VERSION="$(git describe --tags --abbrev=0 --match=''v[0-9]*'' | cut -c2-)-dev-pr-$(git
        rev-parse --short HEAD)-$(date --utc +''%Y%m%d%H%M'')" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_version: ${{ steps.build_variables.outputs.VERSION }}
      name: Build
      run: ./gradlew build ${{ steps.build_variables.outputs.REPO }}-web:installDist
        $GRADLE_ARGS
    - continue-on-error: true
      name: Build slim container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.slim
        platforms: linux/amd64,linux/arm64
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:latest"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:latest-slim"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-slim"

          '
    - continue-on-error: true
      name: Build ubuntu container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.ubuntu
        platforms: linux/amd64,linux/arm64
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:latest-ubuntu"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-ubuntu"

          '
    - continue-on-error: true
      name: Build slim JRE 11 container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.java11.slim
        platforms: linux/amd64,linux/arm64
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:latest-java11"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-java11"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:latest-java11-slim"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-java11-slim"

          '
    - continue-on-error: true
      name: Build ubuntu JRE 11 container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.java11.ubuntu
        platforms: linux/amd64,linux/arm64
        push: false
        tags: '"${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO
          }}:latest-java11-ubuntu"

          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{
          steps.build_variables.outputs.VERSION }}-java11-ubuntu"

          '
  integration-tests:
    name: Integration-tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Gradle validation step
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Run Integration Test
      run: './gradlew kayenta-integration-tests:test --tests ${{ matrix.tests }}Test

        '
    strategy:
      matrix:
        tests:
        - Management
        - Swagger
  provider-integration-tests:
    name: Provider-Integration-tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Gradle validation step
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: '17

          11

          '
    - continue-on-error: true
      name: Run Provider Integration Test
      run: './gradlew kayenta-integration-tests:test --tests ${{ matrix.provider }}StandaloneCanaryAnalysisTest.${{
        matrix.test }}

        '
    strategy:
      matrix:
        provider:
        - Prometheus
        - Graphite
        test:
        - canaryAnalysisIsSuccessful
        - canaryAnalysisIsFailed
name: PR Build
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
